### ISSUE TITLE
학번별 학점DB에 이수체계도, 채플 데이터 등록

### ISSUE THREAD

**Issue by CT-1326** [Team-Helper/ComgongBOT#75]
**올해 학번 데이터 등록은 학과 공용의 이수체계도 데이터와 동기화 필요**

_이수체계도는 15학번부터 이미지 데이터 존재_

**Comment by CT-1326** [comment]
@dh8570 공학, 일반인증 베이스 라인으로 08, 15학번에 채플 혹은 채플&이수체계도 데이터를 삽입함

**Comment by dh8570** [comment]
@CT-1326 DB 데이터 입력 완료했습니다. 확인바랍니다.
