### ISSUE TITLE
이수체계도 이미지 - altText 값 추가

### ISSUE THREAD

**Issue by CT-1326** [Team-Helper/ComgongBOT#87]
DB에 직접 img 태그의 alt 내용 추가

마찬가지로 베이스 라인 내용 참고해서 남은 학번들 채우기 바람

**Comment by dh8570** [comment]
engineeringCredits DB에 imgAlt 값 추가 완료했습니다. 확인바랍니다.

**Comment by CT-1326** [comment]
> engineeringCredits DB에 imgAlt 값 추가 완료했습니다. 확인바랍니다.

GJ!
